name: 🌟 Contribution Acknowledgment
description: Add a contribution acknowledgment
title: "Contribution Acknowledgment: "
labels: [👀 needs triage, 🌟 contribution acknowledgment]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this contribution acknowledgment request!
  - type: dropdown
    attributes:
      multiple: false
      label: Category (from existing repos)
      description: Select the category of the contribution acknowledgment.
      options:
        - "Women In Tech"
        - "Career Growth"
        - "Employment"
        - "Work Environment"
        - "Freelancing"
        - "Community"
        - "Open Source"
    validations:
      required: true
  - type: textarea
    attributes:
      label: Suggested solution
      description: Describe the solution you'd like.
  - type: input
    id: context
    attributes:
      label: Additional context
      description: Add any other context about the contribution acknowledgment or helpful links here.

  - type: checkboxes
    id: assistance
    attributes:
      label: I would be willing to submit a PR to fix this issue
      description: Assistance is provided if you need help submitting a pull request
      options:
        - label: "Yes and I have read the [Contribution Guide]() and I agree to follow this project's [Code of Conduct]()"
        - label: 'No'